#! /bin/sh

#bspc monitor DisplayPort-0 -d 12
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        5
bspc config window_gap          20
bspc config normal_border_color '#c5c8c6'
bspc config active_border_color '#b5bd68'
bspc config focused_border_color '#f0c674'

bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config right_padding 10
#bspc config left_padding 65
#bspc config bottom_padding 10
#bspc config top_padding 40
bspc config initial_polarity second_child

bspc rule -a "Gimp-2.8" desktop=^2 follow=on
#bspc rule -a Screenkey manage=off
bspc rule -a Plasma state=floating manage=off layer=normal
#bspc rule -a krunner state=floating sticky=on
bspc rule -a Klipper state=floating
bspc rule -a plasmashell sticky=on layer=above state=floating
bspc rule -a plasma sticky=on layer=above state=floating
#bspc rule -a latte-dock sticky=on layer=above state=floating
#bspc rule -a lattedock sticky=on layer=above state=floating
bspc rule -a yakuake sticky=on layer=above state=floating
#bspc rule -a jetbrains-idea state=floating
for p in {single,borderless}_monocle; do bspc config "$p" true; done

sxhkd -c ~/.config/sxhkd/sxhkdrc &
#sleep 8
#compton --config ~/.config/compton/compton.conf &
compton &
nitrogen --restore
wicd-client -t &
polybar example &
