call plug#begin('~/.vim/plugged')

    Plug 'vim-pandoc/vim-pandoc'
    Plug 'vim-pandoc/vim-pandoc-syntax'
    Plug 'suan/vim-instant-markdown', {'for': 'markdown'}

call plug#end()

set number	
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set spell
set hlsearch
set smartcase
set ignorecase
set incsearch
set autoindent
set cindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

filetype plugin on
